DefaultWord.create!(question: "鼻の長い動物といえば？", answer: "ぞう", target: "elephant")
DefaultWord.create!(question: "首の長い動物といえば？", answer: "きりん", target: "giraffe")
DefaultWord.create!(question: "白と黒のしましま模様の動物といえば？", answer: "シマウマ", target: "zebra")
DefaultWord.create!(question: "パンジーの和名は？", answer: "さんしきすみれ", target: "sannsikisumire")
DefaultWord.create!(question: "為せば成る、為さねばならぬ何事も、", answer: "成らぬは人の", target: "nasanunarikeri")
DefaultWord.create!(question: "春はあけぼの で始まる随筆は？", answer: "枕草子", target: "makuranosousi")
DefaultWord.create!(question: "源氏物語の作者は？", answer: "紫式部", target: "murasakisikibu")